trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'mydockerhub'
  imageRepository: 'productcatalogue'
  containerRegistry: 'javaprojectacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/java/kubernetes/productcatalogue/Dockerfile'
  tag: '$(Build.BuildId)'
  mavenPomPath: 'java/stockmanager/pom.xml'
  jdkVersion: '1.11'

stages:
- stage: Build
  displayName: Build and Push Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@4
      displayName: 'Build Java Project'
      inputs:
        mavenPomFile: '$(mavenPomPath)'
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(jdkVersion)'
        mavenVersionOption: 'Default'

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)